### ISSUE TITLE
Add support for CouchBase Integration

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1059]
https://github.com/KTHse/cas-server-integration-couchbase

@fjollberg, is KTH still using this module? Are you in production? Why did you decide to use Couchbase? and how easy has it been for you to configure it and withstand the load?

**Comment by fjollberg** [comment]
Yes, we are, however not the very latest version for 4.1.x yet. I updated the code to use the JSON serialiser for the services now included with CAS and hence the upgrade is a bit more complex since we have to recreate our service registry and due to the bug in the management interface we wanted to wait for 4.1.2.

Otherwise, yes, we've been running on versions of this module for almost two years by now without issues. The Couchbase DB is clustered with 3 nodes which we've actually used some time when a node failed, but we've not yet come around to cluster the CAS application itself. It should be almost a no brainer, but we had some issues with our load balancer for a while and had to build up trust with it before we tried that and it has since slipped due to lack of time.

The reason we went with Couchbase was originally as a memcache replacement for Windows, since our CAS production server is run on that OS and we wanted to move the ticket registry out of tomcat memory in a simple manner. From there we wanted to explore the possibilities to create a HA environment in what we believed to be a more robust manner and the step to rewrite the memcache client to a native Couchbase client was rather small. We also considered the clustering properties of Couchbase to be superior to those of MongoDB, the other NoSQL database we were using at our site at the time.

**Comment by fjollberg** [comment]
The one thing that is less than optimal is the CAS behaviour to read the entire contents of the service registry into memory every other minute or so, rather than just look up the service in the registry on request. But that is not something that you can change with a module such as this one and I wanted the module itself it to be an as good CAS citizen as possible.

It works, but changes to the registry in the management interface are not immediately visible, and sometimes you end up in a state where the management UI and the registry is not quite in sync and have to wait for the server to reload the registry.

You may want to make some amendment to the service registry to make it possible to disable the caching behaviour of the registry when you are using appropriate backends.

**Comment by fjollberg** [comment]
While CAS is essential to our services, we do not have very heavy load, so I can't strictly vouch for that. I think the top load we have are a few requests per second. We are using a JMeter test suite for regression and basic load testing where we simulate a load of about 10 various types of requests/second  and typically response time is of the order of tens of milliseconds. I would assume that our couchbase implementation would compare favourably to a traditional RDBMS backend, but I have no statistics to prove it.

**Comment by fjollberg** [comment]
I'll restate here as well that you are very welcome to use our code if you decide to do so.

**Comment by mmoayyed** [comment]
Excellent. Thanks for much for your feedback. I have converted your modules to comply with master's design guidelines. I will submit a PR shortly. Would appreciate it if you could review and comment on any gotchas there.

**Comment by mmoayyed** [comment]
Pull https://github.com/Jasig/cas/pull/1346

**Comment by fjollberg** [comment]
Realised as I went to bed yesterday that the comment about reading the service-registry directly from the database primarily concerns the management web app. The server itself obviously needs to be able to map the regex in the registry to the service parameter in some manner and so realistically needs to preload them into memory.
