### ISSUE TITLE
Release CAS 4.1 GA

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1107]
Announce and discuss on the dev list first.

**Comment by mmoayyed** [comment]
Make sure the latest development docs are moved over to 4.1

**Comment by mmoayyed** [comment]
Planning to cut the release by this Friday per the milestone date. Will post a heads-up announcement to the list to review with the team.

**Comment by leleuj** [comment]
I remember no feedbacks, except my own tests. But I guess we can't wait really more with the RC.

**Comment by mmoayyed** [comment]
Sometimes, no news could be good news :)

**Comment by frittentheke** [comment]
There seems to be an issue with the translations of username or password missing. The message key is simply different in the messages.properties and messages_$LANG.properties files.

required.username vs. username.required / required.password vs. password.required.

Small thing, but why spoil an otherwise nice release for non-english locales ;-)
