### ISSUE TITLE
Break up cas.properties into a set of smaller, cohesive config files

### ISSUE THREAD

**Issue by dima767** [Jasig/cas#1179]
The current `cas.properties` config file is getting bloated and harder to maintain with all kinds of config properties dumped in there. Consider breaking it up into a set of narrowly-focused config files for each configurable logical subsystem of CAS e.g. `cas-core.properties`, `cas-ldap.properties`, `cas-SPNEGO.properties`, etc.

**Comment by leleuj** [comment]
You're right: the `cas.properties` is a too long file. Maybe we should move the properties in the `resources` directory by the way.

**Comment by mmoayyed** [comment]
I think of the following approaches:

1. First, collect every single property into cas.properties file. So that we have an idea where things are that can be configured with CAS. 

2. A big problem with property files is that once they are changed and reloaded, a server restart is required to refresh the context. I want to get away from that limitation, so we'll need to think of a better way to handle that sort of thing. I do think ultimately the prop file has to be replaced by something, don't know what or how yet.

**Comment by dima767** [comment]
Take an inspiration from this -> http://projects.spring.io/spring-cloud/spring-cloud.html#_refresh_scope

**Comment by mmoayyed** [comment]
Handled via #1577
