### ISSUE TITLE
service authorization by hour range

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1188]
Would it be very hard to implement service authorization by hour range? Say I want service X to be enabled only from 8 a.m. to 3 p.m (eventually, also specify the days of the week). Otherwise, refuse authentication.
 
This would be very useful for us in terms of security.

**Comment by dima767** [comment]
I played with Java 8 LocalTime API and it would be very trivial to implement by hour range (without the regard for the client TimeZone and only effective for the CAS server's TimeZone). This could be one simple particular impl. of the `RegisteredServiceAccessStrategy` and if there would be other more complex requirements involving client time zones, etc., more additional impls could be added in the future. Also note that this WILL require Java 8 minimum, but since 4.2 will have the minimum Java 8, I'd say we should just drop this debate whether future CAS (4.2) should support Java 7 or not. Just drop it, already! ;-)

Java 8 Date API is very, very nice and it would look something like this:

```java
LocalTime unavailableStartTime = LocalTime.of(13, 4);
LocalTime unavailableEndTime = LocalTime.of(13, 5);
LocalTime now = LocalTime.now();

boolean serviceUnavailable = now.isAfter(unavailableStartTime) && now.isBefore(unavailableEndTime);
```

**Comment by dima767** [comment]
Oh, I see that you have an impl already. Never mind then. Nothing to see here. Move along ;-)

**Comment by mmoayyed** [comment]
Thanks Dima. I am not entirely sure whether we all agree to bump the version to 8 for a minor release. Probably needs further discussion, and it certainly doesnt break the CAS code. It only imposes a JDK8 requirement to the adopter, which I don't know per release strategy, is something we can do. I am personally fine with it :)

**Comment by mmoayyed** [comment]
P.S: I think it's safe to assume that time-based authZ strategies are solely based off of CAS sever's but we are making it possible to specify timezones in the access strategy config. So that's certainly an option, and I think we are going to go with JodaTime for the time being.

**Comment by leleuj** [comment]
I think it's better to upgrade to JDK 8 for a major version.
