### ISSUE TITLE
Create cache-listeners to handle SLO

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1254]
presently, if a TGT expires as a result of cache policy, SLO notifications are not broadcasted. They only get sent if the logout endpoint is invoked. We have ticket cleaners that do this sort of thing for JPA and Default registries, but nothing for the remaining cache-based registries. This can be achieved via cache listeners that could broadcast SLO calls when they get a TGT expired event.

#1080 must be done first.

**Comment by tduehr** [comment]
A more complete SLO setup also likely needs a way for services to renew a user's TGC, probably by revalidating the ST.

**Comment by mmoayyed** [comment]
renew=true?

**Comment by tduehr** [comment]
No, that forces the user to reauth, I'm thinking the app needs a way to tell CAS the TGC is still in use to it lives at least to either it's max lifetime or the end of all client app sessions using it...

**Comment by tduehr** [comment]
What I meant is the sliding window (default of 2 hours) expiration will always kill an SSO session currently unless there are enough client applications that a user's TGC is updated regularly before the window expires.

That is, if there's only one or two client applications, a user may actively access them throughout the day but their TCG will expire after two hours. This isn't a problem if SLO is disabled or the cache cleaners/listeners aren't fully configured. But, if SLO is enabled and the cache listeners/cleaners are properly configured, the user will be logged out of the client application after two hours despite actively using the client application.

There should be some sort of `/ping` endpoint the client can put in a 1px image to maintain the SSO session.

**Comment by mmoayyed** [comment]
I sympathize with that. At the same time a heartbeat signal defeats the purpose of a sliding window config. If you are unable to manage session timeouts in a consistent way, don't use a sliding window. 

And note that the client will be logged out once either the sliding or hard time out passes. That is SLO.

**Comment by mmoayyed** [comment]
...and if you have applications that user is working with actively throughout the day:

- adjust their session timeouts to a longer value that makes sense. 
- don't use a sliding window config on CAS.

**Comment by tduehr** [comment]
Yes, a javascript heartbeat would defeat the purpose of SSO idle timeouts, a 1px image would only keep the SSO session alive as long as the user visited new pages. For a regular application session idle is determined by page load usually. This doesn't work for SSO sessions since the SSO server is not involved in the application session normally. OpenID does this and SLO by using iframes to communicate session state. SAML2 uses passive requests for this functionality.

The way I expected SLO (and other it seems) to work is:
1. User clicks logout in SP -> SLO triggered
2. SP session times out -> SSO reauth required (no SLO performed)
3. SSO session expires (either idle or max duration) -> SLO triggered

SLO seems to need some coupling between SSO sessions and application sessions.

It's currently possible to have a tiny iframe loading the SSO login page in the application to enable this functionality but it seems clunky.

**Comment by mmoayyed** [comment]
Yes and that is the kind of coupling I am trying to  avoid. CAS is not an app session manager. The sso session is completely distinct from the application at all costs. So if you have applications that are just a few and those are actively used by the user, if does not make sense for you to use a sliding window. You either use a hard timeout on CAS or you increase the application timeout to something that makes sense for the workload of the application. Having the application periodically pining CAS whether it's js calls or something else is unnecessary because not only you are putting extra load on the CAS server, you are asking it to manage the app session for you affectively. That won't happen. There are better and easier alternatives. 

I can sympathize with the issue, but personally I need a better use case to support this sort of feature. Extending the CAS sso timeout sounds like an interesting idea, but I am not yet convinced that use cases are there yet.

**Comment by mmoayyed** [comment]
The cleaner should now run on all registries handling SLO. This https://github.com/Jasig/cas/issues/1580 needs to be worked out. Closing this one.
