### ISSUE TITLE
Documentation issues in 4.1.x

### ISSUE THREAD

**Issue by robertoschwald** [Jasig/cas#1321]
Documentation errors in 4.1.x. PR follows.

**Comment by mmoayyed** [comment]
By the way, if there is anything "custom" that you have that you think might be a good fit to be included in CAS, please don't hesitate to submit other patches.

**Comment by mmoayyed** [comment]
@robertoschwald how is this one going? Were you planning to submit a PR? or was this just a placeholder?

**Comment by PetrGasparik** [comment]
I want to start discussion over LDAP AuthN wiki page. 
The example there is incomplete. For me as new user, to make LDAP authn, I had to define <entry key-ref="ldapAuthenticationHandler" value-ref="usernamePasswordCredentialsResolver" /> 
+    <bean id="usernamePasswordCredentialsResolver"
      class="org.jasig.cas.authentication.principal.BasicPrincipalResolver" />

Plus, I needed to add dependency on SAML library, which is strange.

BUT - because I am newbie, I _might_ overlook something. I would like to ask someone more experienced to repeat my steps. I started branch at 4.1.3 tag and followed just instructions for the LDAP AuthN ("LDAP Requiring Authenticated Search")

**Comment by mmoayyed** [comment]
You can also do:

```
<entry key-ref="ldapAuthenticationHandler" value-ref="#{null}" /> 
```

See http://jasig.github.io/cas/4.1.x/installation/Configuring-Principal-Resolution.html#principalresolver-vs-authenticationhandler

Also, you don't need the SAML module. This was extensively discussed on the list. The docs tell you to:

> You also need to make sure component scanning is turned on when you configure LDAP authentication. Be sure to include the following in the same configuration file that houses the LDAP configuration for CAS:

```
     <context:component-scan base-package="org.jasig.cas" />
     <context:annotation-config/>
```

**Comment by robertoschwald** [comment]
I'm currently migrating old CAS projects and provide PRs of my findings, later.

**Comment by mmoayyed** [comment]
Closing issue for now.
