### ISSUE TITLE
Example That Uses CAS Server 4.1.2 and CAS Client 3.4.1

### ISSUE THREAD

**Issue by rpepersack** [Jasig/cas#1329]
I'm migrating from CAS Server 3 to CAS Server 4.1.2 with Spring Security.  I want to use CAS Client 3.4.1 and CAS Protocol 3.0.  The examples I've found on the web use older versions of CAS and Spring.  I've tried some of the older client example with the new versions of CAS, but they don't work.  Does anyone have a CAS Client that works with the latest versions of CAS Server and CAS Client?

Thanks!

**Comment by leleuj** [comment]
Hi,

I have an example demo with the Spring Security CAS client which is a
little less older:
https://github.com/leleuj/java-spring-security-cas-client-demo
It might help. Otherwise, nothing better than the Spring documentation:
http://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#cas

Thanks.
Best regards,
Jérôme


2015-12-02 14:17 GMT+01:00 rpepersack <notifications@github.com>:
