### ISSUE TITLE
Documentation: 'Throttling Authentication Attempts' - missing 'Throttling Components' part

### ISSUE THREAD

**Issue by aroeber** [Jasig/cas#1391]
Looking at
jasig.github.io/cas/development/installation/Configuring-Authentication-Throttling.html 
the important 'Throttling Components' part is missing.

In 
http://jasig.github.io/cas/4.1.x/installation/Configuring-Authentication-Throttling.html
everything seems to be fine.

**Comment by mmoayyed** [comment]
For that kind of information, you need to consult the javadocs.

**Comment by aroeber** [comment]
Of course javadocs. And I am not really missing this information.  
But what is the reason that (nearly) the same web page does (4.1.x) and does not (development) show this important information. If this is done with intent a hint to the javadocs would be great.

**Comment by mmoayyed** [comment]
The reason is twofold:

1. Configuring those components explicitly via spring beans is no longer necessary. WE/CAS configure them for you. You just have to tell us which one you want to enable.
2. Configuring "beans" requires that you have an understanding of the java/spring framework. 4.1.x docs require you to be a developer to get them. We are moving away from that method. The docs tend to be more deployer-oriented where things are a lot simpler to understand. 

Which is why I am recommending that if you need to understand class names and components and java files and which things are turned on and configured internally, javadocs would the best place to look, or the cas-dev list. 

I'll see if I can add a quick tip somewhere to make that fact better known :)

**Comment by aroeber** [comment]
Thx. Got these arguments.
And a quick tipp would be great.
