### ISSUE TITLE
Add possibility to override the method of cleaning a JpaTicketRegistry?

### ISSUE THREAD

**Issue by aukevanleeuwen** [Jasig/cas#1583]
Hello,

I'm upgrading a CAS 4.0 setup to CAS 4.2 (RC2). I noticed that the `RegistryCleaner` is deprecated in favor for having an implementation directly in `JpaTicketRegistry`. However there isn't really a clean way to override that implementation. I would like to override

```
public void execute(final JobExecutionContext jobExecutionContext) throws JobExecutionException {
 ...
}
```

but the class `JpaTicketRegistry` is `final`. 

For a bit more information about the 'why' I want to override the cleaning mechanism. We have a `RememberMePolicy` of about 90 days. That is: people pretty much stay logged in even though they only log in once in a while. This means we have about 350.000 tickets in our database (with a lot of serialized Java objects). The call `this.getTickets()` in `JpaTicketRegistry#execute()`:

```
final Collection<Ticket> ticketsToRemove = Collections2.filter(this.getTickets(), new Predicate<Ticket>() {
    @Override
    public boolean apply(@Nullable final Ticket ticket) {
       ...
    }
});
```

is assuming that all tickets will fit into memory. This is a bit presumptuous IMHO.

---
As a side question: _why_ are most classes `final` in the CAS codebase? There have been quite a few times where I saw a certain `protected` method which I wanted to override, but I couldn't do that because the class was `final`.

**Comment by mmoayyed** [comment]
No problem with me. Feel free to submit a patch.

As for why final, 2 reasons:
- legacy
- keeping something locked allows the project to make fair mods to the codebase knowing that it will not affect extensions for upgrades. It does have limiting factors, but ideally, it's best to know why something needs opening up rather than leaving everything open to begin with. I personally would want to know why you would want to extend xyz because that somewhat indicates that the project isn't delivering what u want to a certain extent.

I'd much rather see those extensions end up in CAS where appropriate. So, what do u plan tondonwuth your extension? And might it make sense to become part of CAS?

**Comment by frett** [comment]
the ticket cleaning process has been moving around a good bit in 4.2 and 4.3. I know our intention is to make the ticket cleaner more efficient for JPA (see #1199 ) and not need to load all the tickets in memory.

For 4.2 currently it should be possible to disable the built-in JPA ticket cleaner by setting the startDelay to  zero or a negative value. https://github.com/Jasig/cas/blob/4.2.x/cas-server-support-jpa-ticket-registry/src/main/java/org/jasig/cas/ticket/registry/JpaTicketRegistry.java#L313 I would actually consider this currently to be a bug, but we should provide a flag to disable the built-in cleaner process for this use-case and other use cases needing to disable the cleaner process completely.

**Comment by mmoayyed** [comment]
Speaking from memory, but I *think* the flag is built into 4.3. Gotta check.

**Comment by mmoayyed** [comment]
Closing this for now.
