### ISSUE TITLE
The request for google resource block page loading

### ISSUE THREAD

**Issue by benborba** [Jasig/cas#1661]
1. CAS server version: 4.2.0
2. Container type/version (JBoss eap 6.4)

i found that CAS server use some google cdn resources, like below:

src/main/webapp/js/cas.js:    head.load("https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js", loadjQueryUI);
src/main/webapp/js/cas.js:    head.load("https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js", loadjQueryCookies);
src/main/webapp/css/cas.css:/*@import url(https://fonts.googleapis.com/css?family=Lato);*/
src/main/webapp/css/cas.css:@import url(https://fonts.googleapis.com/css?family=Lato:700,400,300,100);

if CAS server was deployed on server in an local intranet, the process of login page loading will be block for a long time.
is that suitable to include these resource into cas project ?

**Comment by frittentheke** [comment]
I used the Maven overlay to get those resources local without fetching ANYTHING from the web. This could be seen as just one aspect of moving away from the provided demo pages in order to create your own CAS installation.

But, as for the issue, apart from loading times, I would like to throw "security" (sic!) into the discussion as, having external java scripts fetched into the login page of your authentication system might not be acceptable for some (read: most) installations.

The main issue might be the licenses and rules to distribute JQuery or the Google Fonts with ones own software.

**Comment by mmoayyed** [comment]
If you're behind a local intranet, you're are more than welcome to change those resources to be local resources. 

Resources should be fetched via `https`. Either you trust SSL or you don't :)
