### ISSUE TITLE
Supplemental Authentications using up memory

### ISSUE THREAD

**Issue by tsschmi** [Jasig/cas#1714]
I have been doing load testing getting ready to update our CAS servers to 4.2.x.  One situation we have seen in the past show up is improperly configured clients that result in them looping requests against our server generating STs.  I created a load test for this situation and saw that our heap memory was quickly being gobbled up, and the TGT being used kept growing in memory size.  After some digging I found that for every request for a ST, the original authentication in the TGT is basically copied into the supplementalAuthentications list with only the authenticationDate being updated to the current time.  I could not think of a reason that the original would not satisfy a policy in this situation, that would require them to look to supplemental authentications.  I changed the following code in CentralAuthenticationServiceImpl to only add to supplemental authentications if the credentials used did not match the original credentials 

```java
    private static Authentication evaluatePossibilityOfMixedPrincipals(final AuthenticationContext context,
                                                                final TicketGrantingTicket ticketGrantingTicket)
            throws MixedPrincipalException {
        Authentication currentAuthentication = null;
        if (context != null) {
            currentAuthentication = context.getAuthentication();
            if (currentAuthentication != null) {
                final Authentication original = ticketGrantingTicket.getAuthentication();
                if (!currentAuthentication.getPrincipal().equals(original.getPrincipal())) {
                    throw new MixedPrincipalException(
                            currentAuthentication, currentAuthentication.getPrincipal(), original.getPrincipal());
                }
                if (!currentAuthentication.getCredentials().equals(original.getCredentials())) {
                    ticketGrantingTicket.getSupplementalAuthentications().add(currentAuthentication);
                }
            }
        }
        return currentAuthentication;
    } 
```

This change made drastic reductions in not only worst case scenarios such as a looping client, but in our normal operational tests as well.

Any reason that this is not a valid modification or does this limit some functionality that I am not seeing?

**Comment by frett** [comment]
in theory supplemental authentications should only be updated when new credentials are being presented, and not when generating just a ST.

**Comment by mmoayyed** [comment]
I have never found any use for `getSupplementalAuthentications`, nor seen it used anywhere that would warrant its existence. Could we get it removed if the use cases are mostly theoretical at this point?

**Comment by dima767** [comment]
+1 for removal

**Comment by frett** [comment]
I'm using it in my overlay on 4.1 in an `AuthenticationPolicy` to detect when a user escalates his LOA by renewing with stronger credentials.

**Comment by mmoayyed** [comment]
Could you elaborate on that please? If I am reading your statement correctly, you have an authentication policy that peeks into the supplemental authentications and decides user should use stronger credentials?

**Comment by frett** [comment]
I'm not directly accessing it, but depending on the fact that those supplemental authentications exist and are checked via `AuthenticationPolicy.isSatisfiedBy`. I haven't looked too closely at the logic since the change to an `AuthenticationBuilder`, so some of that might have changed after 4.1. pulling up the code now to check.

**Comment by frett** [comment]
of course MFA changed the whole paradigm, so I'm sure I'm going to need to re-evaluate whenever I do upgrade.

**Comment by mmoayyed** [comment]
That is sort of where I was going with this, where I think much of what you do today can be done with MFA in general. The supplemental authentications and policies were designed so that folks would implement MFA on their own and take advantage of such policies and APIs. None of that matters anymore since we do MFA natively. As a result, not much use to keeping them around. Policies do play a role and I like them, but the other bit, I can't justify their existence.

**Comment by frett** [comment]
so, my use case is we support Facebook auth and User/Pass auth. Both are tied to the same core user identity. Certain sites require user & pass auth.

So, if a user is currently logged in using facebook auth, whenever they try to visit a site requiring User & Pass auth, we gather additional credentials, and create a new authentication event tracked in Supplemental Auth. We then rely on the AuthenticationPolicy testing logic in `CentralAuthenticationServiceImpl` to test our configured AuthenticationPolicies against all `Authentication` objects for the current TGT.

With the new model of tracking everything in a single Authentication object for MFA, this will all probably change.

**Comment by frett** [comment]
There was also a potential future use case that I was planning on implementing with `AuthenticationPolicy`s. We have 1 service that wants to ensure the user has authenticated within the past 'x' minutes using user name & password credentials. I was planning on utilizing the authentication time data in conjunction with the credentials provided within a single `Authentication` object to see if any of the `Authentication` events met the business rule.

But, that hasn't moved beyond concept level right now, and probably wouldn't before 5.0.0 which introduces MFA and changes quite a bit.

**Comment by mmoayyed** [comment]
Interesting. 

Yes, 5 keeps a single authn instance and continually attempts to update that rather than keeping a recording of authNs and distinguishing between what was original vs what is now renewed. It seems to me that we could in light of that design get rid of supplemental authentications and yet, keep the authentication policies around to meet your need there too. Policies today in master and 4.2 seem far more practical than supplemental authentications.

**Comment by frett** [comment]
I do like the simplification that tracking a single updated `Authentication` object brings. It took me quite a few hours to start to fully grasp the intricacies with having multiple `Authentication` events being satisfied by multiple `AuthenticationPolicies`.

The reason I brought up the potential future use case is because that is something that wouldn't be accurately captured within a single Authentication object currently. But, that requirement on our side is still very open to massaging into a different security requirement that we can satisfy with what CAS provides.

so, +1 to removing them

**Comment by mmoayyed** [comment]
Cool. 

I'd be open to discuss that particular use case but I'd also argue that, that kind of thing should entirely be handled by the application. Of course, if you dont control the app then you may not have a choice :)

**Comment by mmoayyed** [comment]
Starting with this today.

**Comment by dima767** [comment]
Also note that there is a possibility of using new CAS application events and even listeners to capture, track, and act upon such an authentication history, etc. I am currently prototyping this stuff and it looks promising! 

Few things we'd need to think about and do: 1) expose more finer-grained events such as each individual authentication transaction, etc., as well as 2) make much easier to configure SWF execution listeners (currently in master the applicationContext.xml inconsistently configures different flow executors, with login flow being defined by raw beans, making it plugging in SWF execution listeners a rocket science). The SWF listener and CAS events application listener combined in one component makes it possible to expose CAS events data to a flow scope for consumption by downstream SWF components, etc. In a very loosely manner!

Good times! ;-)

**Comment by mmoayyed** [comment]
Great! Look forward to seeing what you have. 

Handling this for the 4.2.x patch release, it's certainly not possible/feasible to get a removal change in. So we need a compromise. Ran some tests, and indeed @tsschmi is right in that authNs are collected into that collection and continue to grow. 

Could we consider keeping the supplemental authNs as is, API-wise, but clear it on every run and only keep a single instance that is the "new" authentication? This is similar to how v5 behaves.

**Comment by dima767** [comment]
Sure. But can we still remove them in v5 (master, after letsboot goes in)?

**Comment by mmoayyed** [comment]
Exactly.
