### ISSUE TITLE
Spring MVC Interceptors didn't works in the snapshot version

### ISSUE THREAD

**Issue by yisiqi** [Jasig/cas#1737]
All modules which used Spring MVC InterceptorRegistry did not works.

I tried the newest OAuth modules. When I access to http://localhost:8080/oauth2.0/authorize..., there is a 404 Error responsed.

**Comment by dima767** [comment]
This ticket lacks any substantial detailed information to be useful for developers in order to help figure out what the problem is. Please try to described in greater detail what you are trying to achieve, how you do it and what exact problems you are facing with any detailed log data from CAS server.

**Comment by yisiqi** [comment]
I just create a new maven project. Copy all the codes from oauth-server-webapp module into the new project. Add required dependencies include oauth-server-support-oauth. Then run `mvn clean spring-boot:run`.

After the server finished startup. I can access `http://localhost:8080/login` to login. But `http://localhost:8080/oauth2.0/authorize?client_id=xxx&redirect_uri=xxx&response_type=code` get a 404 Error.

**Comment by mmoayyed** [comment]
You are affected by https://github.com/Jasig/cas/pull/1731
